services:
  redis:
    image: redis:8
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      REDIS_URL: redis://redis:6379/0
      REAL_IP: "false"
    depends_on:
      - redis
